# Generated by Django 5.2.6 on 2025-12-08 09:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits starting with 6-9', regex='^[6-9]\\d{9}$')])),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Service Provider')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='provider_photos/')),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhar number must be exactly 12 digits', regex='^\\d{12}$')])),
                ('date_of_birth', models.DateField()),
                ('service1', models.CharField(choices=[('mason', 'Mason'), ('painter', 'Painter'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('electrician', 'Electrician'), ('tile_marble', 'Tile/Marble Worker'), ('steel_fabricator', 'Steel Fabricator'), ('glass_worker', 'Glass Worker'), ('gardener', 'Gardener'), ('driver', 'Driver')], max_length=20)),
                ('service2', models.CharField(blank=True, choices=[('mason', 'Mason'), ('painter', 'Painter'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('electrician', 'Electrician'), ('tile_marble', 'Tile/Marble Worker'), ('steel_fabricator', 'Steel Fabricator'), ('glass_worker', 'Glass Worker'), ('gardener', 'Gardener'), ('driver', 'Driver')], max_length=20, null=True)),
                ('service3', models.CharField(blank=True, choices=[('mason', 'Mason'), ('painter', 'Painter'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('electrician', 'Electrician'), ('tile_marble', 'Tile/Marble Worker'), ('steel_fabricator', 'Steel Fabricator'), ('glass_worker', 'Glass Worker'), ('gardener', 'Gardener'), ('driver', 'Driver')], max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='services.customer')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
