# Generated by Django 5.2.6 on 2025-12-08 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('agra', 'Agra'), ('aligarh', 'Aligarh'), ('allahabad', 'Allahabad'), ('ambedkar_nagar', 'Ambedkar Nagar'), ('amethi', 'Amethi'), ('amroha', 'Amroha'), ('auraiya', 'Auraiya'), ('azamgarh', 'Azamgarh'), ('baghpat', 'Baghpat'), ('bahraich', 'Bahraich'), ('ballia', 'Ballia'), ('balrampur', 'Balrampur'), ('banda', 'Banda'), ('barabanki', 'Barabanki'), ('bareilly', 'Bareilly'), ('basti', 'Basti'), ('bhadohi', 'Bhadohi'), ('bijnor', 'Bijnor'), ('budaun', 'Budaun'), ('bulandshahr', 'Bulandshahr'), ('chandauli', 'Chandauli'), ('chitrakoot', 'Chitrakoot'), ('deoria', 'Deoria'), ('etah', 'Etah'), ('etawah', 'Etawah'), ('faizabad', 'Faizabad'), ('farrukhabad', 'Farrukhabad'), ('fatehpur', 'Fatehpur'), ('firozabad', 'Firozabad'), ('gautam_buddha_nagar', 'Gautam Buddha Nagar'), ('ghaziabad', 'Ghaziabad'), ('ghazipur', 'Ghazipur'), ('gonda', 'Gonda'), ('gorakhpur', 'Gorakhpur'), ('hamirpur', 'Hamirpur'), ('hapur', 'Hapur'), ('hardoi', 'Hardoi'), ('hathras', 'Hathras'), ('jalaun', 'Jalaun'), ('jaunpur', 'Jaunpur'), ('jhansi', 'Jhansi'), ('kannauj', 'Kannauj'), ('kanpur_dehat', 'Kanpur Dehat'), ('kanpur_nagar', 'Kanpur Nagar'), ('kasganj', 'Kasganj'), ('kaushambi', 'Kaushambi'), ('kheri', 'Kheri'), ('kushinagar', 'Kushinagar'), ('lalitpur', 'Lalitpur'), ('lucknow', 'Lucknow'), ('maharajganj', 'Maharajganj'), ('mahoba', 'Mahoba'), ('mainpuri', 'Mainpuri'), ('mathura', 'Mathura'), ('mau', 'Mau'), ('meerut', 'Meerut'), ('mirzapur', 'Mirzapur'), ('moradabad', 'Moradabad'), ('muzaffarnagar', 'Muzaffarnagar'), ('pilibhit', 'Pilibhit'), ('pratapgarh', 'Pratapgarh'), ('raebareli', 'Raebareli'), ('rampur', 'Rampur'), ('saharanpur', 'Saharanpur'), ('sambhal', 'Sambhal'), ('sant_kabir_nagar', 'Sant Kabir Nagar'), ('shahjahanpur', 'Shahjahanpur'), ('shamli', 'Shamli'), ('shravasti', 'Shravasti'), ('siddharthnagar', 'Siddharthnagar'), ('sitapur', 'Sitapur'), ('sonbhadra', 'Sonbhadra'), ('sultanpur', 'Sultanpur'), ('unnao', 'Unnao'), ('varanasi', 'Varanasi'), ('mumbai', 'Mumbai'), ('pune', 'Pune'), ('nagpur', 'Nagpur'), ('thane', 'Thane'), ('nashik', 'Nashik'), ('aurangabad', 'Aurangabad'), ('solapur', 'Solapur'), ('kolhapur', 'Kolhapur'), ('amravati', 'Amravati'), ('delhi', 'Delhi'), ('new_delhi', 'New Delhi'), ('north_delhi', 'North Delhi'), ('south_delhi', 'South Delhi'), ('east_delhi', 'East Delhi'), ('west_delhi', 'West Delhi'), ('bengaluru', 'Bengaluru'), ('mysuru', 'Mysuru'), ('hubli', 'Hubli'), ('mangaluru', 'Mangaluru'), ('chennai', 'Chennai'), ('coimbatore', 'Coimbatore'), ('madurai', 'Madurai'), ('tiruchirappalli', 'Tiruchirappalli'), ('kolkata', 'Kolkata'), ('howrah', 'Howrah'), ('durgapur', 'Durgapur'), ('siliguri', 'Siliguri'), ('jaipur', 'Jaipur'), ('jodhpur', 'Jodhpur'), ('kota', 'Kota'), ('udaipur', 'Udaipur'), ('ahmedabad', 'Ahmedabad'), ('surat', 'Surat'), ('vadodara', 'Vadodara'), ('rajkot', 'Rajkot')], default='lucknow', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='district',
            field=models.CharField(choices=[('agra', 'Agra'), ('aligarh', 'Aligarh'), ('allahabad', 'Allahabad'), ('ambedkar_nagar', 'Ambedkar Nagar'), ('amethi', 'Amethi'), ('amroha', 'Amroha'), ('auraiya', 'Auraiya'), ('azamgarh', 'Azamgarh'), ('baghpat', 'Baghpat'), ('bahraich', 'Bahraich'), ('ballia', 'Ballia'), ('balrampur', 'Balrampur'), ('banda', 'Banda'), ('barabanki', 'Barabanki'), ('bareilly', 'Bareilly'), ('basti', 'Basti'), ('bhadohi', 'Bhadohi'), ('bijnor', 'Bijnor'), ('budaun', 'Budaun'), ('bulandshahr', 'Bulandshahr'), ('chandauli', 'Chandauli'), ('chitrakoot', 'Chitrakoot'), ('deoria', 'Deoria'), ('etah', 'Etah'), ('etawah', 'Etawah'), ('faizabad', 'Faizabad'), ('farrukhabad', 'Farrukhabad'), ('fatehpur', 'Fatehpur'), ('firozabad', 'Firozabad'), ('gautam_buddha_nagar', 'Gautam Buddha Nagar'), ('ghaziabad', 'Ghaziabad'), ('ghazipur', 'Ghazipur'), ('gonda', 'Gonda'), ('gorakhpur', 'Gorakhpur'), ('hamirpur', 'Hamirpur'), ('hapur', 'Hapur'), ('hardoi', 'Hardoi'), ('hathras', 'Hathras'), ('jalaun', 'Jalaun'), ('jaunpur', 'Jaunpur'), ('jhansi', 'Jhansi'), ('kannauj', 'Kannauj'), ('kanpur_dehat', 'Kanpur Dehat'), ('kanpur_nagar', 'Kanpur Nagar'), ('kasganj', 'Kasganj'), ('kaushambi', 'Kaushambi'), ('kheri', 'Kheri'), ('kushinagar', 'Kushinagar'), ('lalitpur', 'Lalitpur'), ('lucknow', 'Lucknow'), ('maharajganj', 'Maharajganj'), ('mahoba', 'Mahoba'), ('mainpuri', 'Mainpuri'), ('mathura', 'Mathura'), ('mau', 'Mau'), ('meerut', 'Meerut'), ('mirzapur', 'Mirzapur'), ('moradabad', 'Moradabad'), ('muzaffarnagar', 'Muzaffarnagar'), ('pilibhit', 'Pilibhit'), ('pratapgarh', 'Pratapgarh'), ('raebareli', 'Raebareli'), ('rampur', 'Rampur'), ('saharanpur', 'Saharanpur'), ('sambhal', 'Sambhal'), ('sant_kabir_nagar', 'Sant Kabir Nagar'), ('shahjahanpur', 'Shahjahanpur'), ('shamli', 'Shamli'), ('shravasti', 'Shravasti'), ('siddharthnagar', 'Siddharthnagar'), ('sitapur', 'Sitapur'), ('sonbhadra', 'Sonbhadra'), ('sultanpur', 'Sultanpur'), ('unnao', 'Unnao'), ('varanasi', 'Varanasi'), ('mumbai', 'Mumbai'), ('pune', 'Pune'), ('nagpur', 'Nagpur'), ('thane', 'Thane'), ('nashik', 'Nashik'), ('aurangabad', 'Aurangabad'), ('solapur', 'Solapur'), ('kolhapur', 'Kolhapur'), ('amravati', 'Amravati'), ('delhi', 'Delhi'), ('new_delhi', 'New Delhi'), ('north_delhi', 'North Delhi'), ('south_delhi', 'South Delhi'), ('east_delhi', 'East Delhi'), ('west_delhi', 'West Delhi'), ('bengaluru', 'Bengaluru'), ('mysuru', 'Mysuru'), ('hubli', 'Hubli'), ('mangaluru', 'Mangaluru'), ('chennai', 'Chennai'), ('coimbatore', 'Coimbatore'), ('madurai', 'Madurai'), ('tiruchirappalli', 'Tiruchirappalli'), ('kolkata', 'Kolkata'), ('howrah', 'Howrah'), ('durgapur', 'Durgapur'), ('siliguri', 'Siliguri'), ('jaipur', 'Jaipur'), ('jodhpur', 'Jodhpur'), ('kota', 'Kota'), ('udaipur', 'Udaipur'), ('ahmedabad', 'Ahmedabad'), ('surat', 'Surat'), ('vadodara', 'Vadodara'), ('rajkot', 'Rajkot')], default='lucknow', max_length=50),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='services.customer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'provider')},
            },
        ),
    ]
