# Generated by Django 5.2.6 on 2025-12-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderWorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='work_photos/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_photos', to='services.serviceprovider')),
            ],
            options={
                'verbose_name': 'Work Photo',
                'verbose_name_plural': 'Work Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
